const CRYPTO_ERRORS = ['ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH', 'ERR_OSSL_EVP_BAD_DECRYPT', 'ERR_INVALID_ARG_VALUE'];
const ERR_TOKEN_EXPIRED = 'TokenExpiredError';
const INVALID_TOKEN = 'JsonWebTokenError';
const ALREADY_PROCEEDED = 'AlreadyProceededError';

module.exports = {
  CRYPTO_ERRORS,
  ERR_TOKEN_EXPIRED,
  INVALID_TOKEN,
  ALREADY_PROCEEDED,
};
