const STATUS_INITIATED = 'INITIATED';
const STATUS_PACKAGING = 'PACKAGING';
const STATUS_DELIVERED = 'DELIVERED';
const STATUS_OTP_VR = 'OTP_VR';
const STATUS_EMAIL_VR = 'EMAIL_VR';
const STATUS_PENDING_APR = 'PENDING_APR';
const STATUS_ACTIVE = 'ACTIVE';
const STATUS_PRO_DONE = 'PRO_DONE';
const STATUS_REJECTED = 'REJECTED';
const STATUS_INACTIVE = 'INACTIVE';
const STATUS_TMPLT_SELECTED = 'TMPLT_SELECTED';
const STATUS_APPROVED = 'APPROVED';

module.exports = {
  STATUS_INITIATED,
  STATUS_PACKAGING,
  STATUS_DELIVERED,
  STATUS_OTP_VR,
  STATUS_EMAIL_VR,
  STATUS_PENDING_APR,
  STATUS_ACTIVE,
  STATUS_PRO_DONE,
  STATUS_REJECTED,
  STATUS_INACTIVE,
  STATUS_TMPLT_SELECTED,
  STATUS_APPROVED,
};
